# Generated by Django 4.2.15 on 2024-08-31 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Do_Item',
            new_name='DoItem',
        ),
    ]
