# Generated by Django 4.2.15 on 2024-08-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0002_rename_do_item_doitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='doitem',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doitem',
            name='title',
            field=models.CharField(max_length=288),
        ),
    ]
