# Generated by Django 4.2.15 on 2024-09-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0003_doitem_complete_alter_doitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='doitem',
            name='description',
            field=models.TextField(default='abc'),
            preserve_default=False,
        ),
    ]
