# Generated by Django 4.2.15 on 2024-09-02 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('to_dos', '0004_doitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='doitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='do_items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
