# Generated by Django 4.2.15 on 2024-09-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0008_profileuser_tag_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
