# Generated by Django 4.2.15 on 2024-09-14 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('to_dos', '0009_profileuser_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doitem',
            name='user',
        ),
        migrations.AddField(
            model_name='doitem',
            name='users',
            field=models.ManyToManyField(related_name='do_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
