# Generated by Django 4.2.15 on 2024-09-15 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import to_dos.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('to_dos', '0010_remove_doitem_user_doitem_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='tag_selected',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='tags',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='selected_tag_unique_str',
            field=models.CharField(default=12345678, max_length=8),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Home', max_length=50)),
                ('shared', models.BooleanField(default=False)),
                ('unique_str', models.CharField(default=to_dos.models.create_unique_str, max_length=8)),
                ('users', models.ManyToManyField(related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='doitem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_items', to='to_dos.tag'),
        ),
    ]
