# Generated by Django 4.2.15 on 2024-09-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0011_remove_profileuser_tag_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='amount_supported',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='upgraded',
            field=models.BooleanField(default=False),
        ),
    ]
